networks:
  expense: {}

volumes:
  mysql:

services:
  mysql:
    image: mysql:1.0.0
    container_name: mysql
    networks:
      - expense
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    image: backend:1.0.0
    container_name: backend
    networks:
      - expense
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: frontend:1.0.0
    container_name: frontend
    networks:
      - expense
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started